language: java
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
matrix:
  include:
    - jdk: openjdk8
      dist: xenial
    - jdk: openjdk11
      dist: xenial
    - jdk: oraclejdk8
      dist: trusty
    - jdk: oraclejdk11
      dist: trusty
install:
  - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
deploy:
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
      branch: main

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: K5X3v1dEP7Kg0MUYj8fMwyvEtQVG2iNr0URcEBfdWiH8XSST669p66TKbvo8e9PeZGfAkXJ+aqQBrqjxuNZAdMOOsGSVcIGkO8lOPK0EiiubggnDPUlaaJxm7+kV1IJJLstR5Xnj0t8Mt2adPQia+izG+4lWhTYSN1LtxKzwM0aDu3GnqA4uRRDZvQe44LhXAd3YbUTTZX5geWD7X1QS34iRnAWxmxGulBRoXSVfe0kf8womrz+wksgF/g6+yOxR+teKDogVUnBmBxpua+Z2lSMOLLPwjbRy8Y57M9F4DWpKH96WFQEEBFE0GBs+ygMkMbC5xQ6XEyEF9ArcF2IOxvroCM7wRXvEwnslcinoH11B6PTyUvjQrYB7KSMNpiJAi67f4G/LtoAMgy9lJklG/K7glG9oVSM8eREhGzFUyHsq+zwnCieKi57vb4+BYRoaiSy8Le1oH4sZ53DuXmrP/LStuAb8lP8svSzM8oAltC/NLxSCQt6tdS+CdX7Us/zaqcLtWdgvq1xqFhJiYv1iv3Odi37hRn7F/JhcDzN89BK9hbkCawR2MQ+ND41COzkhs0oEgVTj5gjYUJc9Y2Utac1ONvUF3x0NC3EyjSPiEKgtyYjaa5z+hPkAWR9LMqMQa1pKpfHXwkGsMeXJ4HisKl/L8U3rhccM0h5dkGRIPjU=
