language: java
matrix:
  include:
    - name: 'OpenJDK 7'
      jdk: openjdk7
    - name: 'OpenJDK 8'
      jdk: openjdk8
    - name: 'Oracle JDK 8'
      jdk: oraclejdk8
    - jdk: openjdk11
      name: 'OpenJDK 11'
  allow_failures:
    - name: 'Oracle JDK 8'
    - name: 'OpenJDK 7'
    - name: 'OpenJDK 11'
install:
  - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
deploy:
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
      branch: master
