name: Update dependencies
on:
  schedule:
    # Run automatically at 6AM PST Tuesday
    - cron: '0 6 * * 2'
  workflow_dispatch:

jobs:
  update_dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout java-http-client
        uses: actions/checkout@v2

      - name: Updating semver dependencies
        run: make update-deps

      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.2
        with:
          add: 'pom.xml'
          default_author: 'github_actions'
          message: 'Chore: update sendgrid-java dependencies'

  test:
    name: Test
    if: success()
    needs: [ update_dependencies ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        java: [ 8, 11, 17 ]

    steps:
      - name: Checkout java-http-client
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - run: mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
      - name: Run Unit Tests
        run: mvn test -B

  notify-on-failure:
    name: Slack notify on failure
    if: failure()
    needs: [ update_dependencies, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: failure
          SLACK_ICON_EMOJI: ':github:'
          SLACK_MESSAGE: ${{ format('Update dependencies *{0}*, Test *{1}*, {2}/{3}/actions/runs/{4}', needs.update_dependencies.result, needs.tests.result, github.server_url, github.repository, github.run_id) }}
          SLACK_TITLE: Action Failure - ${{ github.repository }}
          SLACK_USERNAME: GitHub Actions
          SLACK_MSG_AUTHOR: twilio-dx
          SLACK_FOOTER: Posted automatically using GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
